### PR TITLE
feat: IListEmpty and friends

### PR DESCRIPTION
**Pull request by LowLevelSubmarine**
Fix for #75

### CODE REVIEW

**Comment by LowLevelSubmarine** [comment]
I've just added the other Empty types aswell, do you have some suggestion what i could add to the current tests? @marcglasberg

**Comment by LowLevelSubmarine** [comment]
Two things:
Whats your opinion on overriding isEmpty / isNotEmpty on the Empty types like so:
```dart
  /// An empty list is always empty, by definition
  @override
  bool get isEmpty => true;
  
  /// An empty list is always empty, by definition
  @override
  bool get isNotEmpty => false;
```

Do you think we should discourage or even disallow instantiating the IListEmpty directly instead of using IList.empty()?
Although it is one char longer i see the benefit of automatic type coercion beeing IList and not IListEmpty:
```dart
var ilist1 = IList.empty() // is of type IList
var ilist2 = IListEmpty() // is of type IListEmpty
```
I do not see the benefit of having a variable of type FooEmpty, users will always want to reassign the list if they declare an empty ilist right?

**Comment by marcglasberg** [comment]
Yes, you should override all methods that now have trivial implementations, including isEmpty etc. This will make it faster.

And I also see no point in instantiating `IListEmpty` directly, if you can simply write `const ilist1 = IList.empty()` and get an `IList`.

**Comment by LowLevelSubmarine** [comment]
What do you think can we do to discourage instantiating IListEmpty()? We could make the constructors private

**Comment by marcglasberg** [comment]
Yes, sure, make them private.

**Review by marcglasberg — APPROVED** [review]

**Comment by marcglasberg** [comment]
Thanks.

**Pull request merged**
