### PR TITLE
Added method of 5.0.5

### PR DESCRIPTION
**Pull request by Solido**
See changelog

### CODE REVIEW

**Comment by Solido** [comment]
Well maybe up to 5.1 @marcglasberg  ?

**Comment by marcglasberg** [comment]
@Solido did you give up on this PR?

**Comment by Solido** [comment]
I tough I commit too fast.
Already made some breaking changes and still working with others methods
so I commit on my fork better feedback use-cases and not pollute the official repo.

**Comment by marcglasberg** [comment]
At some point in the future we'll have to add a FP section to the Readme.

**Comment by Solido** [comment]
Still open to discuss this point with you and @SandroMaglione 
Can you open another branch so I can maybe merge this work already then see how to add the missing methods ?

**Comment by SandroMaglione** [comment]
@Solido @marcglasberg I just released v0.0.6 of fpdart which included some [functional extension methods](https://github.com/SandroMaglione/fpdart/blob/main/lib/src/list_extension.dart) on `Iterable`.

I would be willing to add the same (and more) methods also to FIC (as extensions or possibly directly inside `IList`). As said, this would mean **adding a dependency on fpdart inside FIC**.

What do you think about this possible solution?

**Comment by Solido** [comment]
Adding a dependency to fp-dart is OK as long as it is an extension with explicit opt-in by import.

At least this is my conception or do you see it directly in core ?

Also a point of attention should be the performance so this is totally ok to use for / while and other optimisation instead of the pure functions compositions.

But of the public API then all rely on Fp-Dart aka Option, Either, etc

**Comment by SandroMaglione** [comment]
> as long as it is an extension with explicit opt-in by import

What do you mean when you say explicit opt-in? If we add functional methods to FIC using fpdart, fpdart must be included as a dependency in the `pubspec.yaml` of FIC. If we then decide for the extension solution, I agree that it should not be exported inside core but it should be opt-in (explicit import).

At its core, the implementation of functional methods does not need to be pure if we want to achieve better performance.

**Comment by Solido** [comment]
Access to FIC
`import 'package:fast_immutable_collections/fast_immutable_collections.dart';`

Access to FP on top of FIC for different methods and coding style
`import 'package:fast_immutable_collections/fast_immutable_collections_fp.dart';`

**Comment by SandroMaglione** [comment]
Yes, I agree 👍

So I would go with the extension methods solution then. What do you think? How do we organize the work?

**Comment by Solido** [comment]
maybe @marcglasberg can open a new branch for fp.
I commit my previous work as a basis for review by @marcglasberg 
Then you can review it to see modifications to help you with `Fic-FP`

Like finding a common ground for Tuple definition but also where to put implementation !
For example I would like it to be a product with arity for later convenience.

Then we start adding method to FP without much dependence on FIC
In parallel add missing methods to FIC like Flat and FoldRight etc

And we keep shared methods for the end.

Maybe adding perfs tests early ?

**Comment by SandroMaglione** [comment]
We should keep in mind that, if FP is introduced through an extension method, extension methods do not override the native implementation. This means that we cannot have a method with the same name both in FIC core and FP extension.

FP, being an extension, should not be dependent on its implementation to FIC core. As you said, we could open a new branch in which we introduce FP on FIC, and then merge when the implementation is stable.

**Comment by Solido** [comment]
`FP, being an extension, should not be dependent on its implementation to FIC core`

If an extension have no dependencies of Lib1 but depends totally to Lib2 then it should belong to Lib2.

If we are adding an extension to Fic that does not depends to Fic then it is not a Fic extension.

FP-Dart-List belongs to FP-Dart as an example, it cannot be used by FIC.

Can you clarify this point ? because the very nature of the definition of **extension** imply it depends on.

**Comment by SandroMaglione** [comment]
> Can you clarify this point ?

I confused the terms 🤔. What I mean is that we should have a new file, say `fast_immutable_collections_fp.dart`, that will be something like this:
```dart
extension FpFicIListExtension<T> on IList<T> {
  /// Implementation...
}
```
The file is external to FIC core, therefore any non-breaking update to FIC should not cause issues to Fp-Fic, as if they were two separate entities.

**Pull request closed without merging**
