### PR TITLE
fix json_serializable generation issue

### PR DESCRIPTION
**Pull request by TimWhiting**
Unfortunately between when I generated the code and when I tested the code for the last pull request I had tried a few alternative ways to get json serialization to work. In doing so, I left in some code that causes json_serializable to emit an error during code-generation. This fixes that error.

### CODE REVIEW

**Comment by TimWhiting** [comment]
@marcglasberg 
Can you take a look at this? Code generation is effectively broken on the dev release. The failing CI seems to be related to switching to flutter beta on CI for getting dependencies, when the library only requires dart and resolves dependencies fine on my computer.

**Comment by marcglasberg** [comment]
@TimWhiting Also runs fine on my machine.

@psygo Oi Phil! Vc saberia dizer porque o CI está falhando, e como consertar isso?

**Comment by psygo** [comment]
@marcglasberg I don't know exactly. I haven't touched anything Dart since February basically. But I vaguely remember a compatibility issue with the `meta` package, I think `flutter_test` was using a different version of it, so there were conflicts. The last version that was working was `1.3.0` apparently, you can check it out on the `pubspec.yaml` file:

https://github.com/marcglasberg/fast_immutable_collections/blob/4028b1dffb03828609c89d621b4c7f1dd5024aaf/pubspec.yaml#L11

Using `flutter_test` was necessary due to it being the only way of using automated `--coverage`, but I don't know if it is the case anymore since I'm not at all up to date with Flutter:

https://github.com/marcglasberg/fast_immutable_collections/blob/4028b1dffb03828609c89d621b4c7f1dd5024aaf/.github/workflows/dart.yml#L38-L39

With respect to `flutter_beta`, I had it on CI because NNBD was not officially available at the time. I suppose you could delete it now, it only takes deleting these lines:

https://github.com/marcglasberg/fast_immutable_collections/blob/4028b1dffb03828609c89d621b4c7f1dd5024aaf/.github/workflows/dart.yml#L23-L24

**Comment by TimWhiting** [comment]
@marcglasberg 
Can we get a dev release for this?

**Pull request merged**
