### PR TITLE
Functional Programming methods introduction & discussion

### PR DESCRIPTION
**Pull request by Solido**
Can be interesting to review where methods should be implemented.
Should we create a specific fp extension for explicit opt-in ?

### CODE REVIEW

**Comment by psygo** [comment]
@SandroMaglione &mdash; author of [fpdart](https://github.com/SandroMaglione/fpdart) &mdash; emailed Marcelo and me recently about introducing more FP patterns using FIC as infrastructure. Maybe he is interested in this too.

**Comment by Solido** [comment]
Depending on the requirements I could foresee 2 

- Enriching FIC with basic FP functions  `Iterable.head -> T`

- (Opt-in) Extensions that make explicit use of [fpdart ](https://github.com/SandroMaglione/fpdart)classes like Option for full featured and efficient collections  `Iterable.headOption -> Option[T]`

**Comment by SandroMaglione** [comment]
If the goal is to introduce FP patterns in FIC, then the first option (`Iterable.head -> T`) does not really work. Every method in functional programming should be safe, therefore it should never throw an exception. This would not be the case if the signature of `head` returns just `T`.

The second option you propose would be better (`Iterable.headOption -> Option[T]`). Nonetheless, it is too easy for any user to skip functional methods when there is a more familiar method available in the same object. For example, if `IList` has both `headOption` and `[0]` to get the first element of the list, most people not familiar with FP will gladly avoid `headOption`. 

Furthermore, **even people that want to introduce FP to their code may forget and use `[0]`**.
***

That being said, I am still thinking about a possible alternative. The options that I currently thought of are:
- Extension methods of FIC (directly inside FIC package or in a separate package entirely). **This option has the problem mentioned above though**.
- Find some way to implement a separate class based on the core of FIC but with **only** functional methods (not sure if possible)
- Use the principles and algorithms of FIC to implement similar immutable collections but with **only** functional methods
- Custom implementation of immutable collections inside fpdart without FIC

I am interested in any other idea or proposal. The requirements in my opinion would be the following:
- Immutability
- Performance
- Only Functional Programming (safe) methods

**Comment by Solido** [comment]
After some thoughs here is my current comprehension about the 2 approach

1.  Easy on-boarding. We rely on existing FIC implementation, it is not pure but effective enough and we can still introduce new effectives methods. `Iterable.head` is the perfect example, you can use it without introducing other structures or dependencies like SemiGroup. It is a good trade-of and transparent to use thus facilitating adoption or integration on existing base code.

2. Pure functionnal. _FIC won't do it_ because you need to review all the foundations and implementations by taking care of the missing support in Dart itself for basic structures aka what you are doing with Dart-FP. Also the design choices in FIC is already set and does not mix well with other goals than performances. It require a lot of understanding of dart itself and fp to get the right choices. Also some features will land on the language later this years and involves a lot of changes.

If expressing a basic statement like `Option**<int>**.none()` already require specific dart  statement, here cast, I am concerned with the complexity of more advanced feature using pure FP.

I would to start to work on an operational implementation enriching FIC now thus gaining some experience, traction and adoption then work on a the much more complete point 2 but later this year when we have more comprehension of requirements and available resources.

**Comment by Solido** [comment]
@marcglasberg Can you merge this one too after review please.
I should have started a dedicated issue instead of transforming the PR on a discussion 
Thx !

**Review by marcglasberg — APPROVED** [review]

**Comment by SandroMaglione** [comment]
@Solido I added some [extension functions](https://github.com/SandroMaglione/fpdart/blob/main/lib/src/list_extension.dart) on `Iterable` to fpdart that implement common functional programming patterns. For now, the extension is on standard dart `Iterable`s.

I would like to see if an extension could be enough. The advantage is that you can still use dart `List` but you now have functional programming functions available which are based on fpdart `Option`, `Either`, etc.

A similar approach could be implemented on `IList`s.

**Comment by Solido** [comment]
Hi Caramba this is great @SandroMaglione !
Love the extension approach and wonder how far we can go.
Kotlin implements nearly everything this way.

Let me recapitulate and complete if I miss some points
We have

- `Fic`: Fast Immutable
- `Fp-Dart Collection` extension for Dart : Pure 
- [Maybe] Fp-Dart extension for FIC : Pure and immutable aka `Fic-Fp`

I would like to find a coherent approach for the whole dart ecosystem so we do not have multiple implementations or at least be as close as possible as a _one stop shop_.

My first idea was to build as much as possible inside FIC using non-pure code for performance/memory reasons.

Then on top of this foundations integrate `Fp-Dart` to expose an FP collections API.
I started putting more methods here https://github.com/marcglasberg/fast_immutable_collections/pull/20
but can overlap with `Fp-Dart Collection` (zip, tuple)

My questions 

- How can we work together on this ecosystem coherent solution[s]
- Where the work should be put right now ?
- How to identify commons ground and shared code ? Looking at you Tuple, List2, etc 
- Do we have some idea about Dart evolution ? evolved Tuples and Enums should first citizens Asap

**Comment by SandroMaglione** [comment]
I would like to see how the '`extension`' solution works for fpdart and if it will eventually have some obvious limitations.

The same approach could be then implemented in FIC (aka `Fic-Fp`). In this case, I think it would be better to add the extension class(es) inside the FIC package. This would mean adding a dependency on fpdart to FIC.

The goal of fpdart would be to provide a solution for immutable collections without implementing it directly inside the package (possibly), but by relying instead on other existing solutions (FIC for example).

> Do we have some idea about Dart evolution?

Looking at the [language funnel](https://github.com/dart-lang/language/projects/1), many functional programming related features are still being discussed. I do not think we can rely on them being ready too soon.

**Comment by Solido** [comment]
Oh nice I see that some methods I have prepared for Fic already landed on FpDart !

For now this clarify the question of `Fic-Fp` ! after 4 years running awesome-flutter my sole concern is good libs not gaining traction because devs do not join forces and so we have too much impls of the same concern.

So the plan could be to add complementary methods to `FIC` and `Fp-Dart` take the charge to reimplement/tests a FP collection on its own thus making `Fic-Fp` a doublon.

So on the ecosystem we have

- Kt-Dart : Strong adoption
- FIC : Gaining traction
- Fp-Dart : Gaining attention

I will put other questions in their respective github repos.

Thanks everyone for the great libs !

**Pull request merged**
